name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  cargo-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libasound2-dev libudev-dev
      - name: Create build cache
        uses: actions/cache@v3
        with:
          key: build-cache
          path: ./target
      - name: Run cargo-check
        run: cargo check

  clippy:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Create build cache
        uses: actions/cache@v3
        with:
          key: build-cache
          path: ./target
      - name: Run clippy
        run: cargo clippy

  cargo-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libasound2-dev libudev-dev
      - name: Create build cache
        uses: actions/cache@v3
        with:
          key: build-cache
          path: ./target
      - name: Run cargo-test
        run: cargo test

  cargo-fmt:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Run cargo-fmt
        run: cargo fmt --check
