name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install build dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libasound2-dev libudev-dev
      - name: Create build cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-release
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - name: Install release dependencies
        run: |
          cargo install just wasm-bindgen-cli
          rustup target add wasm32-unknown-unknown
      - name: Build
        run: just build-release-wasm
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: out/rust-boids-wasm.tar.gz
          makeLatest: true
